name: C++ unit tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test_all:
    name: Test all metrics
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Install BaseGraph
      run: |
        git clone https://github.com/antoineallard/base_graph.git
        cd base_graph
        cmake -B build
        cmake --build build
        cmake --install build --prefix "${{github.workspace}}/local_install"
        pip3 install .
        cd ..

    - name: Configure and build CMake
      run: |
        cmake -B "${{github.workspace}}/build" -DBUILD_TESTS=ON -DCMAKE_PREFIX_PATH="${{github.workspace}}/local_install"
        cmake --build "${{github.workspace}}/build"

    - name: Run unit tests
      working-directory: ${{github.workspace}}/build
      run: ctest --verbose
