seed: 59

algorithm:
  sample_size: 500
  warmup: 2
  thin: 10000
  chain_number: 4
  kernels:
    random walk:
      for: [theta, kappa, beta]
      prob: 1.

generation:
  n: 30
  kappa_min: 4
  kappa_max: 10
  gamma: 2.5
  beta: 2.5
